services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./demo-data:/demo-data:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.python
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend
    restart: unless-stopped
