services:
  backend-free:
    build:
      context: ./backend
      dockerfile: Dockerfile.free
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_TELEMETRY_DISABLED=TRUE
    volumes:
      - ./demo-data:/demo-data:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.python
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend-free
    restart: unless-stopped
